name: precision-irrigation-scheduling
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.49.1
      - tensorflow==2.20.0
      - pandas==2.3.2
      - requests
      - firebase-admin
      - scikit-learn==1.7.1
